name: Get credentials

on:
  workflow_call:
    inputs:
      ENV:
        required: true
        type: string
    secrets:
      SSH_UPSTREAM_HOST:
        required: true
      SSH_UPSTREAM_PORT:
        required: true
      SSH_UPSTREAM_USER:
        required: true
      SSH_UPSTREAM_SECRET_KEY:
        required: true
      SSH_UPSTREAM_FILE_PATH:
        required: true
jobs:
  get-credentials:
    runs-on: linux-amd64
    environment: ${{ inputs.ENV }}
    steps:
      - name: Write secret key
        run: |
            cat<<EOF>ssh_key
            ${SECRET_KEY}
            EOF
            chmod 400 ssh_key
        shell: bash
        env:
          SECRET_KEY: ${{secrets.SSH_UPSTREAM_SECRET_KEY}}

      - name: Get credentials file
        run: |
            scp -o StrictHostKeyChecking=no -i ssh_key -P ${PORT} \
              ${USER}@${HOST}:${FILE_PATH} credentials
        shell: bash
        env:
          PORT: ${{secrets.SSH_UPSTREAM_PORT}}
          USER: ${{secrets.SSH_UPSTREAM_USER}}
          HOST: ${{secrets.SSH_UPSTREAM_HOST}}
          FILE_PATH: ${{secrest.SSH_UPSTREAM_FILE_PATH}}